// WatchTower SOC Dashboard - Main App - PCU FYP 2026
const CONFIG = { LIVE_MODE: false, WAZUH_API: "https://10.10.30.2:9200", REFRESH_MS: 5000, DEMO_MODE: true };
function openTab(id){ document.querySelectorAll('.tab-content').forEach(e=>e.classList.remove('active')); document.querySelectorAll('.tab').forEach(e=>e.classList.remove('active')); document.getElementById(id).classList.add('active'); event.target.classList.add('active'); }
function filterAlerts(){ const q=document.getElementById('searchBox').value.toLowerCase(); const sev=document.getElementById('sevFilter').value; const rows=document.querySelectorAll('#alertBody tr'); rows.forEach(r=>{ const txt=r.innerText.toLowerCase(); const match = txt.includes(q) && (sev===''||txt.includes(sev.toLowerCase())); r.style.display=match?'':'none'; }); }
function exportCSV(){ let csv="timestamp,severity,rule,src,dst,detector,attck\n"; DEMO_ALERTS.forEach(a=>{csv+=`${a.ts},${a.sev},${a.rule},${a.src},${a.dst},${a.det},${a.attck}\n`;}); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download="watchtower_alerts.csv"; a.click(); }
function exportForensic(){ let csv="timestamp,type,src,hash,custody,status\n"; DEMO_FORENSIC.forEach(f=>{csv+=`${f.ts},${f.type},${f.src},${f.hash},${f.custody},${f.status}\n`;}); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download="forensic_log.csv"; a.click(); }
function exportCompliance(){ let txt="WatchTower Compliance Report - PCU FYP 2026\n"; DEMO_COMPLIANCE.forEach(c=>{txt+=`${c.name}: ${c.score}% ${c.status}\n`;}); const blob=new Blob([txt],{type:'text/plain'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download="compliance_report.txt"; a.click(); }
window.onload=()=>{
 document.getElementById('clock').innerText=new Date().toLocaleString();
 const body=document.getElementById('alertBody'); DEMO_ALERTS.forEach(a=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${a.ts}</td><td><span class="sev-${a.sev.toLowerCase()}">${a.sev}</span></td><td>${a.rule}</td><td style="color:#ef4444">${a.src}</td><td>${a.dst}</td><td>${a.det}</td><td>${a.attck}</td>`; body.appendChild(tr); });
 const fwBody=document.getElementById('fwTable'); if(fwBody){ DEMO_FW.forEach(f=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${f.ts}</td><td style="color:${f.act==='BLOCK'?'red':'green'}">${f.act}</td><td>${f.src}</td><td>${f.dst}</td><td>${f.proto}</td><td>${f.port}</td><td>${f.zone}</td><td>${f.rule}</td>`; fwBody.appendChild(tr); }); }
 const compDiv=document.getElementById('complianceBars'); DEMO_COMPLIANCE.forEach(c=>{ const div=document.createElement('div'); const col=c.score>=80?'green':c.score>=70?'orange':'red'; div.innerHTML=`<div>${c.name} <span style="color:${col}">${c.status} ${c.score}%</span><div style="background:#334155;height:8px;border-radius:4px"><div style="width:${c.score}%;background:${col};height:8px;border-radius:4px"></div></div></div>`; compDiv.appendChild(div); });
 const forensicBody=document.getElementById('forensicTable'); if(forensicBody){ DEMO_FORENSIC.forEach(f=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${f.ts}</td><td>${f.type}</td><td>${f.src}</td><td>${f.hash}</td><td>${f.custody}</td><td style="color:${f.status.includes('ANTI')?'red':'green'}">${f.status}</td>`; forensicBody.appendChild(tr); }); }
 // charts
 const ctx1=document.getElementById('alertRateChart').getContext('2d'); new Chart(ctx1,{type:'line',data:{labels:Array.from({length:60},(_,i)=>i),datasets:[{label:'Alerts/min',data:Array.from({length:60},()=>Math.floor(Math.random()*10)+ (Math.random()>0.9?40:0)),borderColor:'#3b82f6',backgroundColor:'rgba(59,130,246,0.2)',fill:true}]},options:{responsive:true}});
 const ctx2=document.getElementById('sevChart').getContext('2d'); new Chart(ctx2,{type:'bar',data:{labels:['Critical','High','Medium','Low'],datasets:[{label:'Count',data:[4,12,38,73],backgroundColor:['#ef4444','#f97316','#eab308','#3b82f6']}]},options:{responsive:true}});
 // live fetch if enabled and not demo
 if(CONFIG.LIVE_MODE && !CONFIG.DEMO_MODE){
   fetch(`${CONFIG.WAZUH_API}/wazuh-alerts-*/_search`,{headers:{'Authorization':'Basic '+btoa('admin:admin')}}).then(r=>r.json()).then(d=>console.log('Live Wazuh data',d)).catch(e=>console.log('Live mode failed, using demo',e));
 }
};
